"""
Data Copilot Lab - Report Generator
Generate professional reports in multiple formats (PDF, HTML, PowerPoint)
"""

import base64
import json
from datetime import datetime
from enum import Enum
from io import BytesIO
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

import pandas as pd
import plotly.graph_objects as go

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter, A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak, Image
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False

try:
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.enum.text import PP_ALIGN
    PPTX_AVAILABLE = True
except ImportError:
    PPTX_AVAILABLE = False

from src.core.exceptions import InvalidParameterError
from src.utils.logger import get_logger

logger = get_logger(__name__)


class ReportFormat(str, Enum):
    """Report output formats"""
    PDF = "pdf"
    HTML = "html"
    PPTX = "pptx"
    MARKDOWN = "markdown"
    JSON = "json"


class ReportSection(str, Enum):
    """Report section types"""
    TITLE = "title"
    SUMMARY = "summary"
    TABLE = "table"
    CHART = "chart"
    TEXT = "text"
    CODE = "code"
    METRICS = "metrics"
    INSIGHTS = "insights"
    RECOMMENDATIONS = "recommendations"


class ReportGenerator:
    """
    Generate professional data science reports

    Supports multiple formats:
    - PDF: Professional reports with charts and tables
    - HTML: Interactive web reports
    - PowerPoint: Presentation slides
    - Markdown: Documentation-style reports
    - JSON: Structured data export
    """

    def __init__(
        self,
        title: str = "Data Analysis Report",
        author: Optional[str] = None,
        company: Optional[str] = None
    ):
        """
        Initialize Report Generator

        Args:
            title: Report title
            author: Report author
            company: Company name
        """
        self.logger = logger
        self.title = title
        self.author = author or "Data Copilot Lab"
        self.company = company or "Generated by Data Copilot Lab"

        self.sections = []
        self.metadata = {
            "title": title,
            "author": self.author,
            "company": self.company,
            "created_at": datetime.now().isoformat()
        }

    def add_title_page(
        self,
        subtitle: Optional[str] = None,
        date: Optional[str] = None
    ):
        """
        Add title page

        Args:
            subtitle: Report subtitle
            date: Report date (None = today)
        """
        self.sections.append({
            "type": ReportSection.TITLE,
            "title": self.title,
            "subtitle": subtitle,
            "author": self.author,
            "company": self.company,
            "date": date or datetime.now().strftime("%Y-%m-%d")
        })

    def add_summary(
        self,
        summary: str,
        key_findings: Optional[List[str]] = None
    ):
        """
        Add executive summary

        Args:
            summary: Summary text
            key_findings: List of key findings
        """
        self.sections.append({
            "type": ReportSection.SUMMARY,
            "summary": summary,
            "key_findings": key_findings or []
        })

    def add_text(
        self,
        title: str,
        content: str,
        level: int = 1
    ):
        """
        Add text section

        Args:
            title: Section title
            content: Text content
            level: Heading level (1-3)
        """
        self.sections.append({
            "type": ReportSection.TEXT,
            "title": title,
            "content": content,
            "level": level
        })

    def add_table(
        self,
        title: str,
        data: pd.DataFrame,
        caption: Optional[str] = None,
        max_rows: int = 50
    ):
        """
        Add data table

        Args:
            title: Table title
            data: DataFrame
            caption: Table caption
            max_rows: Maximum rows to include
        """
        # Limit rows
        if len(data) > max_rows:
            data_sample = data.head(max_rows)
            caption = (caption or "") + f" (showing {max_rows} of {len(data)} rows)"
        else:
            data_sample = data

        self.sections.append({
            "type": ReportSection.TABLE,
            "title": title,
            "data": data_sample,
            "caption": caption
        })

    def add_chart(
        self,
        title: str,
        figure: go.Figure,
        caption: Optional[str] = None
    ):
        """
        Add chart/visualization

        Args:
            title: Chart title
            figure: Plotly figure
            caption: Chart caption
        """
        self.sections.append({
            "type": ReportSection.CHART,
            "title": title,
            "figure": figure,
            "caption": caption
        })

    def add_metrics(
        self,
        title: str,
        metrics: Dict[str, Any],
        description: Optional[str] = None
    ):
        """
        Add metrics section

        Args:
            title: Section title
            metrics: Dictionary of metrics
            description: Metrics description
        """
        self.sections.append({
            "type": ReportSection.METRICS,
            "title": title,
            "metrics": metrics,
            "description": description
        })

    def add_code(
        self,
        title: str,
        code: str,
        language: str = "python"
    ):
        """
        Add code block

        Args:
            title: Code section title
            code: Code content
            language: Programming language
        """
        self.sections.append({
            "type": ReportSection.CODE,
            "title": title,
            "code": code,
            "language": language
        })

    def add_insights(
        self,
        title: str,
        insights: List[str]
    ):
        """
        Add insights section

        Args:
            title: Section title
            insights: List of insights
        """
        self.sections.append({
            "type": ReportSection.INSIGHTS,
            "title": title,
            "insights": insights
        })

    def add_recommendations(
        self,
        title: str,
        recommendations: List[Dict[str, str]]
    ):
        """
        Add recommendations

        Args:
            title: Section title
            recommendations: List of recommendations with 'title', 'description', 'priority'
        """
        self.sections.append({
            "type": ReportSection.RECOMMENDATIONS,
            "title": title,
            "recommendations": recommendations
        })

    def generate(
        self,
        output_path: Union[str, Path],
        format: Union[str, ReportFormat] = ReportFormat.HTML
    ) -> str:
        """
        Generate report

        Args:
            output_path: Output file path
            format: Report format

        Returns:
            Output file path
        """
        if isinstance(format, str):
            format = ReportFormat(format)

        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        self.logger.info(f"Generating {format.value} report: {output_path}")

        if format == ReportFormat.HTML:
            result = self._generate_html(output_path)
        elif format == ReportFormat.PDF:
            result = self._generate_pdf(output_path)
        elif format == ReportFormat.PPTX:
            result = self._generate_pptx(output_path)
        elif format == ReportFormat.MARKDOWN:
            result = self._generate_markdown(output_path)
        elif format == ReportFormat.JSON:
            result = self._generate_json(output_path)
        else:
            raise InvalidParameterError(f"Format {format} not supported")

        self.logger.info(f"Report generated: {result}")

        return str(result)

    def _generate_html(self, output_path: Path) -> Path:
        """Generate HTML report"""
        html_parts = []

        # HTML header
        html_parts.append("""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px;
            border-radius: 10px;
            margin-bottom: 30px;
            text-align: center;
        }}
        .header h1 {{
            margin: 0;
            font-size: 2.5em;
        }}
        .header p {{
            margin: 10px 0 0 0;
            opacity: 0.9;
        }}
        .section {{
            background: white;
            padding: 30px;
            margin-bottom: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        h2 {{
            color: #667eea;
            border-bottom: 2px solid #667eea;
            padding-bottom: 10px;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }}
        th, td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }}
        th {{
            background-color: #667eea;
            color: white;
        }}
        tr:hover {{
            background-color: #f5f5f5;
        }}
        .metrics {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin: 20px 0;
        }}
        .metric {{
            background: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
            border-left: 4px solid #667eea;
        }}
        .metric-value {{
            font-size: 2em;
            font-weight: bold;
            color: #667eea;
        }}
        .metric-label {{
            color: #666;
            font-size: 0.9em;
            margin-top: 5px;
        }}
        .insights, .recommendations {{
            list-style: none;
            padding: 0;
        }}
        .insights li, .recommendations li {{
            padding: 15px;
            margin: 10px 0;
            background: #f8f9fa;
            border-left: 4px solid #28a745;
            border-radius: 4px;
        }}
        .recommendations li {{
            border-left-color: #ffc107;
        }}
        code {{
            background: #f4f4f4;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
        }}
        pre {{
            background: #f4f4f4;
            padding: 15px;
            border-radius: 5px;
            overflow-x: auto;
        }}
        .footer {{
            text-align: center;
            padding: 20px;
            color: #666;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
""".format(title=self.title))

        # Generate sections
        chart_counter = 0
        for section in self.sections:
            if section['type'] == ReportSection.TITLE:
                html_parts.append(f"""
    <div class="header">
        <h1>{section['title']}</h1>
        {f"<p style='font-size:1.2em'>{section['subtitle']}</p>" if section.get('subtitle') else ""}
        <p>{section['author']}</p>
        <p>{section['company']}</p>
        <p>{section['date']}</p>
    </div>
""")

            elif section['type'] == ReportSection.TEXT:
                html_parts.append(f"""
    <div class="section">
        <h{section['level'] + 1}>{section['title']}</h{section['level'] + 1}>
        <p>{section['content']}</p>
    </div>
""")

            elif section['type'] == ReportSection.TABLE:
                table_html = section['data'].to_html(index=False, classes='data-table')
                html_parts.append(f"""
    <div class="section">
        <h2>{section['title']}</h2>
        {table_html}
        {f"<p><em>{section['caption']}</em></p>" if section.get('caption') else ""}
    </div>
""")

            elif section['type'] == ReportSection.CHART:
                chart_id = f"chart_{chart_counter}"
                chart_counter += 1
                chart_json = section['figure'].to_json()

                html_parts.append(f"""
    <div class="section">
        <h2>{section['title']}</h2>
        <div id="{chart_id}"></div>
        {f"<p><em>{section['caption']}</em></p>" if section.get('caption') else ""}
        <script>
            var chartData = {chart_json};
            Plotly.newPlot('{chart_id}', chartData.data, chartData.layout);
        </script>
    </div>
""")

            elif section['type'] == ReportSection.METRICS:
                metrics_html = '<div class="metrics">'
                for key, value in section['metrics'].items():
                    metrics_html += f"""
        <div class="metric">
            <div class="metric-value">{value}</div>
            <div class="metric-label">{key}</div>
        </div>
"""
                metrics_html += '</div>'

                html_parts.append(f"""
    <div class="section">
        <h2>{section['title']}</h2>
        {f"<p>{section['description']}</p>" if section.get('description') else ""}
        {metrics_html}
    </div>
""")

            elif section['type'] == ReportSection.INSIGHTS:
                insights_html = '<ul class="insights">'
                for insight in section['insights']:
                    insights_html += f'<li>{insight}</li>'
                insights_html += '</ul>'

                html_parts.append(f"""
    <div class="section">
        <h2>{section['title']}</h2>
        {insights_html}
    </div>
""")

            elif section['type'] == ReportSection.RECOMMENDATIONS:
                recs_html = '<ul class="recommendations">'
                for rec in section['recommendations']:
                    recs_html += f"""<li>
        <strong>{rec.get('title', 'Recommendation')}</strong>
        {f" (Priority: {rec.get('priority', 'medium')})" if rec.get('priority') else ""}
        <br>{rec.get('description', '')}
    </li>"""
                recs_html += '</ul>'

                html_parts.append(f"""
    <div class="section">
        <h2>{section['title']}</h2>
        {recs_html}
    </div>
""")

        # Footer
        html_parts.append(f"""
    <div class="footer">
        <p>Generated by Data Copilot Lab on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
    </div>
</body>
</html>
""")

        # Write file
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(''.join(html_parts))

        return output_path

    def _generate_pdf(self, output_path: Path) -> Path:
        """Generate PDF report"""
        if not REPORTLAB_AVAILABLE:
            raise InvalidParameterError("ReportLab not installed. Install with: pip install reportlab")

        doc = SimpleDocTemplate(str(output_path), pagesize=letter)
        story = []
        styles = getSampleStyleSheet()

        # Title page
        for section in self.sections:
            if section['type'] == ReportSection.TITLE:
                story.append(Spacer(1, 2*inch))
                title_style = ParagraphStyle('CustomTitle', parent=styles['Heading1'], fontSize=24, textColor=colors.HexColor('#667eea'), alignment=1)
                story.append(Paragraph(section['title'], title_style))
                story.append(Spacer(1, 0.3*inch))

                if section.get('subtitle'):
                    story.append(Paragraph(section['subtitle'], styles['Heading2']))
                    story.append(Spacer(1, 0.2*inch))

                story.append(Paragraph(section['author'], styles['Normal']))
                story.append(Paragraph(section['company'], styles['Normal']))
                story.append(Paragraph(section['date'], styles['Normal']))
                story.append(PageBreak())

            elif section['type'] == ReportSection.TEXT:
                story.append(Paragraph(section['title'], styles['Heading2']))
                story.append(Spacer(1, 0.1*inch))
                story.append(Paragraph(section['content'], styles['Normal']))
                story.append(Spacer(1, 0.3*inch))

            elif section['type'] == ReportSection.TABLE:
                story.append(Paragraph(section['title'], styles['Heading2']))
                story.append(Spacer(1, 0.1*inch))

                # Convert DataFrame to table
                data = [section['data'].columns.tolist()] + section['data'].values.tolist()
                t = Table(data)
                t.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#667eea')),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, 0), 12),
                    ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                    ('GRID', (0, 0), (-1, -1), 1, colors.black)
                ]))
                story.append(t)
                story.append(Spacer(1, 0.3*inch))

            elif section['type'] == ReportSection.METRICS:
                story.append(Paragraph(section['title'], styles['Heading2']))
                story.append(Spacer(1, 0.1*inch))

                if section.get('description'):
                    story.append(Paragraph(section['description'], styles['Normal']))
                    story.append(Spacer(1, 0.1*inch))

                # Create metrics table
                metrics_data = [[k, str(v)] for k, v in section['metrics'].items()]
                t = Table(metrics_data)
                t.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f8f9fa')),
                    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                    ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                    ('GRID', (0, 0), (-1, -1), 1, colors.gray)
                ]))
                story.append(t)
                story.append(Spacer(1, 0.3*inch))

        doc.build(story)
        return output_path

    def _generate_pptx(self, output_path: Path) -> Path:
        """Generate PowerPoint presentation"""
        if not PPTX_AVAILABLE:
            raise InvalidParameterError("python-pptx not installed. Install with: pip install python-pptx")

        prs = Presentation()
        prs.slide_width = Inches(10)
        prs.slide_height = Inches(7.5)

        for section in self.sections:
            if section['type'] == ReportSection.TITLE:
                slide = prs.slides.add_slide(prs.slide_layouts[0])  # Title slide
                title = slide.shapes.title
                subtitle = slide.placeholders[1]

                title.text = section['title']
                subtitle.text = f"{section['author']}\n{section['company']}\n{section['date']}"

            elif section['type'] == ReportSection.TEXT:
                slide = prs.slides.add_slide(prs.slide_layouts[1])  # Title and content
                title = slide.shapes.title
                content = slide.placeholders[1]

                title.text = section['title']
                content.text = section['content']

            elif section['type'] == ReportSection.TABLE:
                slide = prs.slides.add_slide(prs.slide_layouts[5])  # Blank
                title = slide.shapes.title
                title.text = section['title']

                # Add table (simplified - just first few rows)
                data = section['data'].head(10)
                rows, cols = len(data) + 1, len(data.columns)

                left = Inches(1)
                top = Inches(2)
                width = Inches(8)
                height = Inches(4)

                table = slide.shapes.add_table(rows, cols, left, top, width, height).table

                # Headers
                for col_idx, col_name in enumerate(data.columns):
                    table.cell(0, col_idx).text = str(col_name)

                # Data
                for row_idx, row in enumerate(data.itertuples(index=False), 1):
                    for col_idx, value in enumerate(row):
                        table.cell(row_idx, col_idx).text = str(value)

        prs.save(str(output_path))
        return output_path

    def _generate_markdown(self, output_path: Path) -> Path:
        """Generate Markdown report"""
        md_parts = []

        for section in self.sections:
            if section['type'] == ReportSection.TITLE:
                md_parts.append(f"# {section['title']}\n")
                if section.get('subtitle'):
                    md_parts.append(f"## {section['subtitle']}\n")
                md_parts.append(f"\n**Author:** {section['author']}\n")
                md_parts.append(f"**Company:** {section['company']}\n")
                md_parts.append(f"**Date:** {section['date']}\n\n---\n\n")

            elif section['type'] == ReportSection.TEXT:
                md_parts.append(f"{'#' * (section['level'] + 1)} {section['title']}\n\n")
                md_parts.append(f"{section['content']}\n\n")

            elif section['type'] == ReportSection.TABLE:
                md_parts.append(f"## {section['title']}\n\n")
                md_parts.append(section['data'].to_markdown())
                md_parts.append("\n\n")

            elif section['type'] == ReportSection.METRICS:
                md_parts.append(f"## {section['title']}\n\n")
                for key, value in section['metrics'].items():
                    md_parts.append(f"- **{key}**: {value}\n")
                md_parts.append("\n")

            elif section['type'] == ReportSection.INSIGHTS:
                md_parts.append(f"## {section['title']}\n\n")
                for insight in section['insights']:
                    md_parts.append(f"- {insight}\n")
                md_parts.append("\n")

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(''.join(md_parts))

        return output_path

    def _generate_json(self, output_path: Path) -> Path:
        """Generate JSON report"""
        report_data = {
            "metadata": self.metadata,
            "sections": []
        }

        for section in self.sections:
            section_data = {"type": section['type'].value}

            # Convert DataFrames to dict
            for key, value in section.items():
                if isinstance(value, pd.DataFrame):
                    section_data[key] = value.to_dict('records')
                elif isinstance(value, go.Figure):
                    section_data[key] = "plotly_figure"  # Can't serialize figure
                elif key != 'type':
                    section_data[key] = value

            report_data["sections"].append(section_data)

        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(report_data, f, indent=2, default=str)

        return output_path

    def get_section_count(self) -> int:
        """Get number of sections"""
        return len(self.sections)

    def clear_sections(self):
        """Clear all sections"""
        self.sections = []
